### ISSUE TITLE
List of SSv2 Events

### ISSUE THREAD

**Issue by Hritikbansal** [bpiyush/TestOfTime#3]
Hi @bpiyush ,

Which 49 actions out of 174 actions in the SSv2-Template were considered for SSv2 events? Based on the instructions in the paper, I checked the number of captions > 1 verbs in them and found 80 of them. I am using the following snippet to check this:

```
    from collections import Counter
    
    import spacy
    nlp = spacy.load("en_core_web_sm")
    caption_pos_tags = Counter([token.pos_ for token in nlp(caption)])
    if 'VERB' in caption_pos_tags:
        if caption_pos_tags['VERB'] > 1:
            multi_event += 1
```

The breakdown I get is as follows:
2 VERBS: 56
3 VERBS: 21
4 VERBS: 3

Some 4 verb examples:

```
Caption: Pretending or trying and failing to twist [something]
POS: ['VERB', 'CCONJ', 'VERB', 'CCONJ', 'VERB', 'PART', 'VERB', 'X', 'PRON', 'PUNCT']
```

**Comment by bpiyush** [comment]
Hi @Hritikbansal,

Actually, we used instances with exactly two verbs. So in your case, the 56 numbers is correct.

I used huggingface's [flair POS tagger](https://huggingface.co/flair/pos-english) which yielded only 49 instances with two verbs. So the discrepancy is due to a different POS tagger. 

For consistency, I am attaching a CSV with each SSv2 class template labelled as having a composition of two verbs or not. You could use that.
[ssv2_autodetected_compositional_classes.csv](https://github.com/bpiyush/TestOfTime/files/12605257/ssv2_autodetected_compositional_classes.csv)

I hope this helps?

**Comment by Hritikbansal** [comment]
Thanks! Sounds good. The phrasing in the paper was a bit confusing then.
